name: ci
on:
  push:
    branches:
      - master 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-techdocs-core
      - run: pip install mkdocs-video
      #- run: pip install mkdocs-multirepo-plugin
      #- run: pip install mkdocs-git-revision-date-plugin
      #- run: pip install python-slugify
      - run: mkdocs gh-deploy --force