# The GitHub personal access token used in this deploy expires on September 1, 2023.
name: ci 
on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: 3.x
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: actions/cache@v3
        id: cache
        with:
          key: ${{ runner.os }}-${{ hashFiles('.cache/**') }}
          path: .cache
      - run: pip install -r requirements.txt
      - run: pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
      - run: make deploy